table Date
	lineageTag: 8e9a357e-eebc-4caa-97f9-f9e91137ac02
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: c3565ff2-464e-416f-aa8e-e5e38be012b7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e54982db-9da3-402e-946f-543367b89728
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: bb43fc78-4550-4abf-8ccd-bbc9e99d76f7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b3a9c33b-8724-4a81-9d9c-6919cc4151e8
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: 04223b53-34a0-4c9e-93f0-0764f44341ee
		summarizeBy: none
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 9c8b84d3-9eeb-4259-9c36-8b1c37b9bbe4
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 6071d261-a4d8-43b6-ad89-02ca1476614f
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: f0011402-a522-4d00-9df4-92eedc3681ec
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 154a89d9-92db-4c24-b22c-31f7dfbd34e6

		level Date
			lineageTag: bbe28571-01d4-463e-bde0-4198f1821940
			column: Date

		level Month
			lineageTag: 5084c3b9-b724-4c01-b41e-f6d2337da64c
			column: Month

	partition Date = m
		mode: import
		source =
				let
				    Source = Sql.Databases("myfreesqldbserver66.database.windows.net"),
				    earthquake_analysis = Source{[Name="earthquake_analysis"]}[Data],
				    dbo_Date = earthquake_analysis{[Schema="dbo",Item="Date"]}[Data],
				    #"Inserted Month Name" = Table.AddColumn(dbo_Date, "Month Name", each Date.MonthName([Date]), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Month Name",{{"Month Name", "month_name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

