table eq_data
	lineageTag: e7fce76b-fe4c-4397-97b2-ccda2a66756b

	measure latest_eq_date = ```
			
			    CALCULATE(
			        MAX(eq_data[event_date]),
			        ALL(eq_data)
			    )
			```
		formatString: dd/mm/yy
		lineageTag: 8c2a7a3b-0ce6-4a87-87d3-a2ec4a992414

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure latest_eq_time = ```
			
			    CALCULATE(
			        MAX(eq_data[event_time]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date]
			        )
			    )
			```
		formatString: hh:nn:ss
		lineageTag: d1eff32e-abdd-48e1-a30b-6cd52855096d

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure latest_eq_lat = ```
			
			    CALCULATE(
			        MAX(eq_data[latitude]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			```
		lineageTag: 1e763647-5f93-4ac0-bfcd-0653e11383c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure latest_eq_lon = ```
			
			    CALCULATE(
			        MAX(eq_data[longitude]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			```
		lineageTag: 3019335c-d24a-498c-ab91-1d10297d81e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure latest_eq_elevation = ```
			
			    CALCULATE(
			        MAX(eq_data[elevation]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			```
		formatString: 0.00
		lineageTag: ac2f482d-694f-4772-b36c-5ceee83982c4

	measure eq_count = COUNTROWS(eq_data)
		formatString: 0
		lineageTag: de6cf259-58cd-4ebe-94c1-7c4e53e8865a

	measure eq_count_last_24h = ```
			
			    CALCULATE(
			        COUNTROWS(eq_data),
			        FILTER(
			            ALL(eq_data),
			           eq_data[event_date] + eq_data[event_time] > NOW() - 1
			        ))
			```
		formatString: 0
		lineageTag: 54c7523f-c89b-401c-a4ad-fdc9ef9f543d

	measure latest_eq_location = ```
			
			    var city = 
			        CALCULATE(
			            MAX(eq_data[City]),
			            FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			    var country = 
			        CALCULATE(
			            MAX(eq_data[Country]),
			            FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			    var state = 
			        CALCULATE(
			            MAX(eq_data[State]),
			            FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			    RETURN
			        city & ", " & state & ", " & country
			
			```
		lineageTag: d177fcb2-740f-4969-bfb6-4e83cb152202

	measure eq_count_last_7d = ```
			
			    CALCULATE(
			        COUNTROWS(eq_data),
			        FILTER(
			            ALL(eq_data),
			           eq_data[event_date] + eq_data[event_time] > NOW() - 7
			        ))
			```
		formatString: 0
		lineageTag: 56c7bc76-fe84-4530-aa68-4aad7a338e6d

	measure eq_count_last_30d = ```
			
			    CALCULATE(
			        COUNTROWS(eq_data),
			        FILTER(
			            ALL(eq_data),
			           eq_data[event_date] + eq_data[event_time] > NOW() - 30
			        ))
			```
		formatString: 0
		lineageTag: f661c466-9f71-43aa-87e7-003f1721e199

	measure eq_count_last_6M = ```
			
			    CALCULATE(
			        COUNTROWS(eq_data),
			        FILTER(
			            ALL(eq_data),
			           eq_data[event_date] + eq_data[event_time] > NOW() - 180
			        ))
			```
		formatString: #,0
		lineageTag: a599dc85-ac7d-4f1e-a4b3-182f8d2e32cf

	measure max_mag_last_24h = ```
			
			    CALCULATE(
			        MAX(eq_data[magnitude]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] + eq_data[event_time] >= NOW() - 1
			        )
			    )
			```
		lineageTag: d4bb7084-2b62-4fbf-9a88-cebea054f0cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure latest_eq_mag = ```
			
			    CALCULATE(
			        MAX(eq_data[magnitude]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			```
		lineageTag: bce6b0a6-2fcb-4ab2-bcaa-9af36698783e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure latest_eq_desc = ```
			
			    CALCULATE(
			        MAX(eq_data[place_description]),
			        FILTER(
			            ALL(eq_data),
			            eq_data[event_date] = [latest_eq_date] && eq_data[event_time] = [latest_eq_time]
			        )
			    )
			```
		lineageTag: 919ff26d-b2ac-4c9a-ac32-a7b3e400edce

	measure eq_type =
			
			VAR Magnitude = SELECTEDVALUE(eq_data[magnitude])
			RETURN
			SWITCH(
			    TRUE(),
			    Magnitude < 3.0, "Minor",
			    Magnitude < 5.0, "Light",
			    Magnitude < 7.0, "Moderate",
			    Magnitude < 9.0, "Strong",
			    Magnitude >= 9.0, "Massive",
			    "Unknown"
			)
		lineageTag: 5fa4a3ba-89c0-4960-8ded-ec05621be877

	measure time_from_last_eq = ```
			
			    NOW() - ([latest_eq_date] + [latest_eq_time])
			```
		formatString: hh:nn:ss
		lineageTag: 3ace0c7d-b5f7-47ea-ba45-a71596a5cea7

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure within_last_24_hrs =
			
			IF (
			    (MAX (eq_data[event_date]) + MAX(eq_data[event_time])) >= NOW() - 1,
			    1,
			    0
			)
		formatString: 0
		lineageTag: ce490d5d-967a-4c91-8034-d24fafec81db

	measure max_mag = max(eq_data[magnitude])
		lineageTag: 1dc2a6be-b1bb-40e0-9f02-6bf771594263

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Most Common Severity' = ```
			
			    VAR TopSeverity =
			        TOPN (
			            1,
			            SUMMARIZE (
			                eq_data,
			                eq_data[EarthquakeType],
			                "SeverityCount", COUNTROWS ( eq_data )
			            ),
			            [SeverityCount], DESC
			        )
			    RETURN
			        MAXX ( TopSeverity, eq_data[EarthquakeType] )
			```
		lineageTag: 376263e2-aac4-4e2a-936a-fc5a26feab00

	measure eq_above_5% = ```
			
			    var eq_count_above_5 = 
			        CALCULATE(
			            COUNTROWS(eq_data),
			            FILTER(
			                eq_data,
			                eq_data[magnitude]>=5
			        )
			    )
			    var total_eq_count = COUNTROWS(eq_data)
			
			    RETURN 
			        DIVIDE( eq_count_above_5, total_eq_count) 
			    
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 04dd9358-73ba-4636-8e22-cc576c87a212

	column id
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a2b1bab0-e9d3-4691-8ef6-da3ee0ba7ccf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		sourceProviderType: float
		lineageTag: 2a46c8b4-ddd7-484a-8245-7cc08c273bd7
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column latitude
		dataType: double
		sourceProviderType: float
		lineageTag: 55d9606c-0f5b-48e9-9987-29464c78edb8
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column elevation
		dataType: double
		sourceProviderType: float
		lineageTag: 2253da58-37fb-4d6d-9267-e2dde1210973
		summarizeBy: sum
		sourceColumn: elevation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column title
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 75c409ed-be4e-4232-a1c5-778818d38b63
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column magnitude
		dataType: double
		sourceProviderType: float
		lineageTag: 49ad8192-08a4-4899-b6f5-d5db6fcc9dc6
		summarizeBy: sum
		sourceColumn: magnitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column place_description
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 24627490-2167-46d5-bcde-bf6c300e2fdb
		summarizeBy: none
		sourceColumn: place_description

		annotation SummarizationSetBy = Automatic

	column sig
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2f409568-a16b-4b30-bd19-24b9eafc1da9
		summarizeBy: sum
		sourceColumn: sig

		annotation SummarizationSetBy = Automatic

	column magType
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 91a95baf-3d5c-4216-810c-c3dc4d1524a1
		summarizeBy: none
		sourceColumn: magType

		annotation SummarizationSetBy = Automatic

	column event_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d25bd95-096d-4f6c-8947-e1b1f6480e4f
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column event_time
		dataType: dateTime
		formatString: Long Time
		sourceProviderType: nvarchar(max)
		lineageTag: 1206e097-85aa-4e10-b885-1efa1af3a219
		summarizeBy: none
		sourceColumn: event_time

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column City
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 8ee36243-1d15-4898-ac37-6515e6349ca0
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country_Code
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 4948393a-461c-4690-8fa1-4ead781f5ac4
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 64326b5a-6cd5-4f7c-be87-abda8bc02a95
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: cd4204c9-843d-4725-b7cd-3b4955fe9d19
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column EarthquakeType =
			
			SWITCH(
			    TRUE(),
			    [Magnitude] < 3.0, "Minor (<3.0)",
			    [Magnitude] < 5.0, "Light (3.0–4.9)",
			    [Magnitude] < 7.0, "Moderate (5.0–6.9)",
			    [Magnitude] < 9.0, "Strong (7.0–8.9)",
			    [Magnitude] >= 9.0, "Massive (>=9.0)"
			)
		lineageTag: 858a6e7b-66c5-47b2-91ae-f8710ad1c34c
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Continent =
			
			SWITCH(
			    TRUE(),
			    -- North America / Central America / Caribbean
			    'eq_data'[Country] IN {
			        "United States", "Canada", "Mexico", "Greenland", "Costa Rica", "Guatemala", "El Salvador", "Panama", "Nicaragua",
			        "Puerto Rico", "Virgin Islands, British", "Virgin Islands, U.S.", "Barbados", "Grenada", "Dominica", "Antigua and Barbuda",
			        "Trinidad and Tobago", "Haiti", "Dominican Republic", "Anguilla", "Bonaire, Sint Eustatius and Saba",
			        "Honduras", "Saint Kitts and Nevis", "Cayman Islands",
			        "Turks and Caicos Islands", "Sint Maarten (Dutch part)", "Martinique", "Saint Barthélemy",
			        "Guadeloupe"
			    }, "N America",
			    -- South America
			    'eq_data'[Country] IN {
			        "Argentina", "Brazil", "Chile", "Bolivia, Plurinational State of", "Colombia", "Peru", "French Guiana", "Venezuela, Bolivarian Republic of",
			        "Ecuador", "South Georgia and the South Sandwich Islands",
			        "Falkland Islands (Malvinas)"
			    }, "S America",
			    -- Asia
			    'eq_data'[Country] IN {
			        "Kazakhstan", "Turkmenistan", "Uzbekistan", "Tajikistan", "Mongolia", "China",
			        "Taiwan, Province of China", "Japan", "Philippines", "Indonesia", "Malaysia", "Timor-Leste",
			        "Christmas Island", "Cocos (Keeling) Islands",
			        "India", "Pakistan", "Nepal", "Iran, Islamic Republic of", "Afghanistan", "Maldives", "Yemen", "Oman", "Saudi Arabia",
			        "Myanmar", "Bhutan", "Azerbaijan", "Kyrgyzstan",
			        "Viet Nam", "Thailand", "Iraq", "Qatar", "Kuwait", "Georgia", "Armenia",
			        "Türkiye","Russian Federation"
			    }, "Asia",
			    -- Oceania
			    'eq_data'[Country] IN {
			        "Australia", "New Zealand", "Wallis and Futuna", "Tonga",
			        "Guam", "Northern Mariana Islands",
			        "Samoa", "Palau",
			        "Pitcairn", "Norfolk Island",
			        "New Caledonia", "Papua New Guinea", "Solomon Islands", "Vanuatu", "Fiji", "Micronesia, Federated States of"
			    }, "Oceania",
			    -- Africa
			    'eq_data'[Country] IN {
			        "Morocco", "Ethiopia", "Madagascar", "South Africa", "Tanzania, United Republic of", "Somalia", "Malawi",
			        "Mauritius", "Djibouti", "Burundi", "Equatorial Guinea", "Réunion", "Tunisia", "Sudan",
			        "Algeria", "Chad", "Zimbabwe", "Uganda", "Eritrea", "Gabon", "Congo, The Democratic Republic of the", "Rwanda", "Libya",
			        "Saint Helena, Ascension and Tristan da Cunha"
			    }, "Africa",
			    -- Europe
			    'eq_data'[Country] IN {
			        "Portugal", "Greece", "Poland", "Spain", "Albania", "Iceland", "Norway", "Cyprus", "Svalbard and Jan Mayen",
			        "Malta", "Italy", "Hungary",
			        "France", "Bosnia and Herzegovina", "Croatia", "Romania",
			        "Russia"
			    }, "Europe",
			    -- Antarctica
			    'eq_data'[Country] IN {
			        "Antarctica", "French Southern Territories"
			    }, "Antarctica",
			    "Other"
			)
		lineageTag: 492266ef-4472-4171-a0df-0977f6e11c0f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition eq_data = m
		mode: import
		source =
				let
				    Source = Sql.Database("myfreesqldbserver66.database.windows.net", "earthquake_analysis", [Query="select * from gold_data where magnitude > 0"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"event_date", type date}}),
				    #"Extracted First Characters" = Table.TransformColumns(#"Changed Type", {{"event_time", each Text.Start(_, 8), type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Extracted First Characters",{{"updated_date", type date}}),
				    #"Extracted First Characters1" = Table.TransformColumns(#"Changed Type1", {{"updated_time", each Text.Start(_, 8), type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Extracted First Characters1",{"updated_time", "updated_date"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

